import React from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '@homeberris/layouts/Navbar';
import Footer from '@homeberris/layouts/Footer';
import CategoryMenu from '@homeberris/components/CategoryMenu';
import styles from '@homeberris/styles/Home.module.css';
import BottomBarMobile from '../BottomBarMobile';
import { useCookies } from 'react-cookie';

export type MainContainerProps = {
  children: React.ReactNode;
  title?: string;
};
const inter = Inter({ subsets: ['latin'] });

const MainContainer = ({ children, title }: MainContainerProps) => {

  return (
    <React.Fragment>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='theme-color' content='#667eea' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={[styles.main, inter.className].join(' ')}>
        <Navbar />
        
        {/* <CategoryMenu /> */}
        <section className={styles.sectionTwo}>{children}</section>
        {/* <Footer /> */}
        <BottomBarMobile />
      </main>
    </React.Fragment>
  );
};

export default MainContainer;
